name: shattered-pixel-dungeon
version: "v3.2.0"
summary: LibGDX port of the awesome Pixel Dungeon
description: |
  Shattered Pixel Dungeon is a Roguelike RPG, with pixel art graphics and lots
  of variety and replayability. Every game is unique, with four different 
  playable characters, randomized levels and enemies, and over 150 items to 
  collect and use. The game is simple to get into, but has lots of depth. 
  Strategy is required if you want to win! 
base: core22
compression: lzo

grade: stable
confinement: strict

architectures:
  - build-on: amd64

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib

apps:
  shattered-pixel-dungeon:
    extensions: [ gnome ]
    command: "bin/Shattered_Pixel_Dungeon"
    environment:
      ALSA_CONFIG_PATH: "$SNAP/etc/asound.conf"
    plugs:
      - joystick
      - audio-playback
      - audio-record
      - alsa
      - network
      - network-bind
      - home
      - removable-media

parts:
  alsa-pulseaudio:
    plugin: dump
    source: .
    override-pull: |
      mkdir etc -p
      cat > etc/asound.conf <<EOF
      pcm.!default {
          type pulse
          fallback "sysdefault"
          hint {
              show on
              description "Default ALSA Output (currently PulseAudio Sound Server)"
          }
      }
      ctl.!default {
          type pulse
          fallback "sysdefault"
      }
      EOF
  shattered-pixel-dungeon:
    after: [alsa-pulseaudio]
    plugin: dump
    source: https://github.com/00-Evan/shattered-pixel-dungeon/releases/download/$SNAPCRAFT_PROJECT_VERSION/ShatteredPD-$SNAPCRAFT_PROJECT_VERSION-Linux.zip
    override-build: |
      craftctl default
      mv "$SNAPCRAFT_PART_INSTALL/bin/Shattered Pixel Dungeon" "$SNAPCRAFT_PART_INSTALL/bin/Shattered_Pixel_Dungeon"
      mv "$SNAPCRAFT_PART_INSTALL/lib/app/Shattered Pixel Dungeon.cfg" "$SNAPCRAFT_PART_INSTALL/lib/app/Shattered_Pixel_Dungeon.cfg"
