name: 🧪 Test snap builds on x86_64

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Show log on build failure
        if: ${{ failure() }}
        run: |
          cat /home/runner/.local/state/snapcraft/log/snapcraft*.log
          exit 1

      - name: Review snap
        uses: diddlesnaps/snapcraft-review-action@v1
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          isClassic: 'false'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: 'snap'
          path: ${{ steps.snapcraft.outputs.snap}}
